// flow-typed signature: a73b0042663b5ec6b3f158976552e32c
// flow-typed version: <<STUB>>/@publica/url-polyfill_v^0.5.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@publica/url-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@publica/url-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@publica/url-polyfill/testharness' {
  declare module.exports: any;
}

declare module '@publica/url-polyfill/testharnessreport' {
  declare module.exports: any;
}

declare module '@publica/url-polyfill/url' {
  declare module.exports: any;
}

declare module '@publica/url-polyfill/urltestparser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@publica/url-polyfill/testharness.js' {
  declare module.exports: $Exports<'@publica/url-polyfill/testharness'>;
}
declare module '@publica/url-polyfill/testharnessreport.js' {
  declare module.exports: $Exports<'@publica/url-polyfill/testharnessreport'>;
}
declare module '@publica/url-polyfill/url.js' {
  declare module.exports: $Exports<'@publica/url-polyfill/url'>;
}
declare module '@publica/url-polyfill/urltestparser.js' {
  declare module.exports: $Exports<'@publica/url-polyfill/urltestparser'>;
}
