// flow-typed signature: 7973b3fe8a0098ba4083725e834e3ce7
// flow-typed version: <<STUB>>/dom-delegate_v^2.0.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-delegate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-delegate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-delegate/build/dom-delegate' {
  declare module.exports: any;
}

declare module 'dom-delegate/build/dom-delegate.min' {
  declare module.exports: any;
}

declare module 'dom-delegate/GruntFile' {
  declare module.exports: any;
}

declare module 'dom-delegate/lib/delegate' {
  declare module.exports: any;
}

declare module 'dom-delegate/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-delegate/build/dom-delegate.js' {
  declare module.exports: $Exports<'dom-delegate/build/dom-delegate'>;
}
declare module 'dom-delegate/build/dom-delegate.min.js' {
  declare module.exports: $Exports<'dom-delegate/build/dom-delegate.min'>;
}
declare module 'dom-delegate/GruntFile.js' {
  declare module.exports: $Exports<'dom-delegate/GruntFile'>;
}
declare module 'dom-delegate/lib/delegate.js' {
  declare module.exports: $Exports<'dom-delegate/lib/delegate'>;
}
declare module 'dom-delegate/lib/index.js' {
  declare module.exports: $Exports<'dom-delegate/lib/index'>;
}
