// flow-typed signature: 2baa0fed0f81ebc61b4b6320f3e01562
// flow-typed version: <<STUB>>/dosomething-modal_v^0.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dosomething-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dosomething-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dosomething-modal/dist/modal' {
  declare module.exports: any;
}

declare module 'dosomething-modal/dist/modernizr' {
  declare module.exports: any;
}

declare module 'dosomething-modal/lib/events' {
  declare module.exports: any;
}

declare module 'dosomething-modal/lib/index' {
  declare module.exports: any;
}

declare module 'dosomething-modal/lib/modal' {
  declare module.exports: any;
}

declare module 'dosomething-modal/src/events' {
  declare module.exports: any;
}

declare module 'dosomething-modal/src/index' {
  declare module.exports: any;
}

declare module 'dosomething-modal/src/modal' {
  declare module.exports: any;
}

declare module 'dosomething-modal/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dosomething-modal/dist/modal.js' {
  declare module.exports: $Exports<'dosomething-modal/dist/modal'>;
}
declare module 'dosomething-modal/dist/modernizr.js' {
  declare module.exports: $Exports<'dosomething-modal/dist/modernizr'>;
}
declare module 'dosomething-modal/lib/events.js' {
  declare module.exports: $Exports<'dosomething-modal/lib/events'>;
}
declare module 'dosomething-modal/lib/index.js' {
  declare module.exports: $Exports<'dosomething-modal/lib/index'>;
}
declare module 'dosomething-modal/lib/modal.js' {
  declare module.exports: $Exports<'dosomething-modal/lib/modal'>;
}
declare module 'dosomething-modal/src/events.js' {
  declare module.exports: $Exports<'dosomething-modal/src/events'>;
}
declare module 'dosomething-modal/src/index.js' {
  declare module.exports: $Exports<'dosomething-modal/src/index'>;
}
declare module 'dosomething-modal/src/modal.js' {
  declare module.exports: $Exports<'dosomething-modal/src/modal'>;
}
declare module 'dosomething-modal/webpack.config.js' {
  declare module.exports: $Exports<'dosomething-modal/webpack.config'>;
}
