// flow-typed signature: b013ad3b7f7dd08380549775e1e7f76e
// flow-typed version: <<STUB>>/sixpack-client_v^2.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sixpack-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sixpack-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sixpack-client/examples/node/basic' {
  declare module.exports: any;
}

declare module 'sixpack-client/sixpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sixpack-client/examples/node/basic.js' {
  declare module.exports: $Exports<'sixpack-client/examples/node/basic'>;
}
declare module 'sixpack-client/sixpack.js' {
  declare module.exports: $Exports<'sixpack-client/sixpack'>;
}
