// flow-typed signature: 8118d48cb57f6f7fb3e8aa86a80dbce5
// flow-typed version: <<STUB>>/@dosomething/analytics_v^2.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dosomething/analytics/analytics' {
  declare module.exports: any;
}

declare module '@dosomething/analytics/dist/Analytics' {
  declare module.exports: any;
}

declare module '@dosomething/analytics/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dosomething/analytics/analytics.js' {
  declare module.exports: $Exports<'@dosomething/analytics/analytics'>;
}
declare module '@dosomething/analytics/dist/Analytics.js' {
  declare module.exports: $Exports<'@dosomething/analytics/dist/Analytics'>;
}
declare module '@dosomething/analytics/webpack.config.js' {
  declare module.exports: $Exports<'@dosomething/analytics/webpack.config'>;
}
