// flow-typed signature: 713b9d6554ff3830c349bbb29d3e48db
// flow-typed version: <<STUB>>/@dosomething/eslint-config_v^3.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@dosomething/eslint-config/index' {
  declare module.exports: $Exports<'@dosomething/eslint-config'>;
}
declare module '@dosomething/eslint-config/index.js' {
  declare module.exports: $Exports<'@dosomething/eslint-config'>;
}
