// flow-typed signature: 051d0b81bc9253cff6b42d39bff45503
// flow-typed version: <<STUB>>/@dosomething/forge_v^6.7.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/forge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/forge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dosomething/forge/dist/forge' {
  declare module.exports: any;
}

declare module '@dosomething/forge/dist/modernizr' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/feature-detect/label-click' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/footer' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/footnote' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/index' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/jump-scroll' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/messages' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/navigation' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/scroll-indicator' {
  declare module.exports: any;
}

declare module '@dosomething/forge/js/tabs' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/feature-detect/label-click' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/footer' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/footnote' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/index' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/jump-scroll' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/messages' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/navigation' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/scroll-indicator' {
  declare module.exports: any;
}

declare module '@dosomething/forge/lib/tabs' {
  declare module.exports: any;
}

declare module '@dosomething/forge/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dosomething/forge/dist/forge.js' {
  declare module.exports: $Exports<'@dosomething/forge/dist/forge'>;
}
declare module '@dosomething/forge/dist/modernizr.js' {
  declare module.exports: $Exports<'@dosomething/forge/dist/modernizr'>;
}
declare module '@dosomething/forge/index' {
  declare module.exports: $Exports<'@dosomething/forge'>;
}
declare module '@dosomething/forge/index.js' {
  declare module.exports: $Exports<'@dosomething/forge'>;
}
declare module '@dosomething/forge/js/feature-detect/label-click.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/feature-detect/label-click'>;
}
declare module '@dosomething/forge/js/footer.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/footer'>;
}
declare module '@dosomething/forge/js/footnote.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/footnote'>;
}
declare module '@dosomething/forge/js/index.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/index'>;
}
declare module '@dosomething/forge/js/jump-scroll.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/jump-scroll'>;
}
declare module '@dosomething/forge/js/messages.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/messages'>;
}
declare module '@dosomething/forge/js/navigation.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/navigation'>;
}
declare module '@dosomething/forge/js/scroll-indicator.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/scroll-indicator'>;
}
declare module '@dosomething/forge/js/tabs.js' {
  declare module.exports: $Exports<'@dosomething/forge/js/tabs'>;
}
declare module '@dosomething/forge/lib/feature-detect/label-click.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/feature-detect/label-click'>;
}
declare module '@dosomething/forge/lib/footer.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/footer'>;
}
declare module '@dosomething/forge/lib/footnote.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/footnote'>;
}
declare module '@dosomething/forge/lib/index.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/index'>;
}
declare module '@dosomething/forge/lib/jump-scroll.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/jump-scroll'>;
}
declare module '@dosomething/forge/lib/messages.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/messages'>;
}
declare module '@dosomething/forge/lib/navigation.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/navigation'>;
}
declare module '@dosomething/forge/lib/scroll-indicator.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/scroll-indicator'>;
}
declare module '@dosomething/forge/lib/tabs.js' {
  declare module.exports: $Exports<'@dosomething/forge/lib/tabs'>;
}
declare module '@dosomething/forge/webpack.config.js' {
  declare module.exports: $Exports<'@dosomething/forge/webpack.config'>;
}
