// flow-typed signature: 6a9f8c5c3c4931c12fb2b12d23c5e755
// flow-typed version: <<STUB>>/@dosomething/gateway_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dosomething/gateway'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dosomething/gateway' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dosomething/gateway/dist/gateway' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/lib/gateway' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/lib/Northstar' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/lib/Phoenix' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/lib/PhoenixAshes' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/lib/RestApiClient' {
  declare module.exports: any;
}

declare module '@dosomething/gateway/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dosomething/gateway/dist/gateway.js' {
  declare module.exports: $Exports<'@dosomething/gateway/dist/gateway'>;
}
declare module '@dosomething/gateway/lib/gateway.js' {
  declare module.exports: $Exports<'@dosomething/gateway/lib/gateway'>;
}
declare module '@dosomething/gateway/lib/Northstar.js' {
  declare module.exports: $Exports<'@dosomething/gateway/lib/Northstar'>;
}
declare module '@dosomething/gateway/lib/Phoenix.js' {
  declare module.exports: $Exports<'@dosomething/gateway/lib/Phoenix'>;
}
declare module '@dosomething/gateway/lib/PhoenixAshes.js' {
  declare module.exports: $Exports<'@dosomething/gateway/lib/PhoenixAshes'>;
}
declare module '@dosomething/gateway/lib/RestApiClient.js' {
  declare module.exports: $Exports<'@dosomething/gateway/lib/RestApiClient'>;
}
declare module '@dosomething/gateway/webpack.config.js' {
  declare module.exports: $Exports<'@dosomething/gateway/webpack.config'>;
}
